configuration:
  version: 1.0
  name: smpp_gateway
  test_sms: 
    -
      enabled: true
      port: 9393
  delay_per_second: 8.0
  time_to_retry: 10
  dlr_port: 9292
  dlr_mask: 31
  kannel:
    daemon_bearerbox: /usr/local/kannel/sbin/bearerbox
    daemon_smsbox: /usr/local/kannel/sbin/smsbox
    conf_file: /etc/kannel/kannel.conf
  api_server_port: 8000
  channels:
    - 
      name: "Turnos"
      pool_size: 3
      activemq_topic_sender: com.smpp_gateway.turnos.sender
      activemq_topic_receiver: com.smpp_gateway.turnos.receiver
      activemq_topic_response: com.smpp_gateway.turnos.response
      receiver_expression: '^(turno|turnos)'
      short_number: 0972444000
      kannel_user: TURNOS
      kannel_pass: abc12345
      kannel_url: http://localhost:13013/cgi-bin/sendsms
      api_server:
        enabled: false
        users:
          -
            name: "turnos_user"
            pass: "abc12345@@"
      default: 1
    -
      name: "Bulk"
      pool_size: 3
      activemq_topic_sender: com.smpp_gateway.bulk.sender
      activemq_topic_receiver: com.smpp_gateway.bulk.receiver
      activemq_topic_response: com.smpp_gateway.bulk.response
      receiver_expression: '^(bulk|bul)'
      short_number: 0972444000
      kannel_user: BULK
      kannel_pass: abc12345
      kannel_url: http://localhost:13013/cgi-bin/sendsms
      api_server:
        enabled: true
        users:
          -
            name: "bulk_user"
            pass: "abc12345@@"
      default: 0